name: Build-Deploy-Frontend
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: messageapplicationcontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build . -t messageapplicationcontainerregistry.azurecr.io/frontend-image:${{ github.sha }}
          docker push messageapplicationcontainerregistry.azurecr.io/frontend-image:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update --name exr-138-frontend \
            --resource-group EXR-DEV-QA \
            --image messageapplicationcontainerregistry.azurecr.io/frontend-image:${{ github.sha }}
